# Generated by Django 3.2 on 2022-03-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_file_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='feature_path',
            field=models.TextField(default='', verbose_name='特征文件路径'),
        ),
    ]
