# Generated by Django 3.2 on 2022-04-11 08:26

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_newuser_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='img',
            field=models.FileField(default='', upload_to=user.models.user_directory_path, verbose_name='用户头像'),
        ),
    ]
