# Generated by Django 3.2 on 2022-05-04 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('view', '0004_alter_viewpic3d_pic_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewindex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vic_name', models.CharField(default='', max_length=50, verbose_name='图片名称')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('viewpic', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='view.viewpic')),
            ],
        ),
    ]
