# Generated by Django 3.2 on 2022-05-04 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0003_alter_viewindex_viewpic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Viewindex',
            new_name='Viewleft',
        ),
        migrations.CreateModel(
            name='Viewright',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vic_name', models.CharField(default='', max_length=50, verbose_name='图片名称')),
                ('viewpic', models.CharField(default='-1', max_length=10, verbose_name='链接图片id')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
