# Generated by Django 3.2 on 2022-03-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0005_remove_experiment_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_train',
            name='data_path',
            field=models.TextField(default='', verbose_name='数据路径'),
        ),
        migrations.AddField(
            model_name='model_train',
            name='train_index',
            field=models.TextField(default='', verbose_name='训练需要保存的参数'),
        ),
    ]
