# Generated by Django 3.2 on 2022-05-11 02:16

from django.db import migrations, models
import model.models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0008_model_train_result_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_train',
            name='pre',
            field=models.BooleanField(default=False, verbose_name='是否预测'),
        ),
        migrations.AddField(
            model_name='model_train',
            name='pre_result',
            field=models.FileField(default='', upload_to=model.models.user_directory_path4, verbose_name='预测结果'),
        ),
        migrations.DeleteModel(
            name='Experiment',
        ),
    ]
