# Generated by Django 2.2 on 2022-03-13 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import view.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewpic3d',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(default='', max_length=20, verbose_name='图片类型')),
                ('pic_name', models.CharField(default='', max_length=20, verbose_name='图片名称')),
                ('data_file', models.FileField(default='', upload_to=view.models.user_directory_path3d, verbose_name='图片数据')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Viewpic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(default='', max_length=20, verbose_name='图片类型')),
                ('pic_name', models.CharField(default='', max_length=20, verbose_name='图片名称')),
                ('data_file', models.FileField(default='', upload_to=view.models.user_directory_path, verbose_name='图片数据')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
