# Generated by Django 3.2 on 2022-03-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewpic3d',
            name='other_index',
            field=models.TextField(default='', verbose_name='其他信息'),
        ),
    ]
