# Generated by Django 3.2 on 2022-05-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0003_alter_viewpic_pic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewpic3d',
            name='pic_name',
            field=models.CharField(default='', max_length=50, verbose_name='图片名称'),
        ),
    ]
